require("vince.plugins-setup")
require("vince.core.options")
require("vince.core.keymaps")
require("vince.core.colorscheme")
require("vince.plugins.comment")
require("vince.plugins.nvim-tree")
require("vince.plugins.lualine")
require("vince.plugins.telescope")
